name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

permissions:
  contents: read
jobs:

  check:
    runs-on: ubuntu-latest
    name: Check w/ ${{ matrix.deno-version }}
    strategy:
      matrix:
        deno-version:
        - v2.0
        - v2.1
        - v2.2
        - v2.3
        - v2.4
        - v2.5
        - canary
      fail-fast: false # run each branch to completion

    steps:
    - name: Checkout source
      uses: actions/checkout@v5

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Cache Deno deps
      uses: actions/cache@v4
      with:
        path: ~/.cache/deno
        key: denodir/${{ matrix.deno-version }}-${{ hashFiles('deno.lock') }}

    - name: Possibly reset lockfile
      run: deno install || rm deno.lock

    - name: Check demo.ts
      run: time deno check demo.ts

    - name: Check mod.ts
      run: time deno check mod.ts

    # - name: Run tests
    #   run: time deno test --allow-net=localhost --allow-read=/proc/self


  check-publish:
    runs-on: ubuntu-latest
    name: Check JSR rules

    steps:
    - name: Checkout source
      uses: actions/checkout@v5

    - name: Set up Deno
      uses: denoland/setup-deno@v2

    - name: Cache Deno deps
      uses: actions/cache@v4
      with:
        path: ~/.cache/deno
        key: denodir/publish-${{ hashFiles('deno.lock') }}

    - name: Check publish rules
      run: deno publish --dry-run --allow-dirty

  rebundle-otel:
    runs-on: ubuntu-latest
    name: Rebundle OpenTelemetry

    steps:
    - name: Checkout source
      uses: actions/checkout@v5
      with:
        submodules: true

    - name: Set up Deno
      uses: denoland/setup-deno@v2

    - name: Cache Deno deps
      uses: actions/cache@v4
      with:
        path: ~/.cache/deno
        key: denodir/rebundle-${{ hashFiles('deno.lock') }}

    - name: Cache npm
      uses: actions/cache@v4
      with:
        path: ~/.cache/deno/npm
        key: deno-npm/v1-${{ github.sha }}
        restore-keys: deno-npm/v1-

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        # cache: 'yarn'

    - name: Build
      run: hack/bundle-opentelemetry.ts

    - name: Status
      run: git status

    - name: Check demo.ts
      run: deno check demo.ts

  publish:
    runs-on: ubuntu-latest
    needs:
    - check
    - check-publish
    - rebundle-otel
    if: github.event_name == 'push'

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v5
      with:
        submodules: true

    - name: Set up Deno
      uses: denoland/setup-deno@v2

    - name: Cache Deno deps
      uses: actions/cache@v4
      with:
        path: ~/.cache/deno
        key: denodir/publish-${{ hashFiles('deno.lock') }}

    - name: Publish now
      run: deno publish
